language: r

# Be strict when checking package
warnings_are_errors: true

before_install:
  - git clone https://github.com/jpmml/openscoring.git
  - cd openscoring
  - mvn clean install
  - java -jar openscoring-server/target/server-executable-1.2-SNAPSHOT.jar &
  - sleep 3
  - curl -X GET http://localhost:8080/openscoring/model
  
# System dependencies for HTTP calling
r_binary_packages:
 - testthat
